name: ex_u_and_i
description: "Flutter Study conunt Date"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/img/

  fonts:
    - family: nanum
      fonts:
        - asset: asset/font/NanumBrush.ttf
        - asset: asset/font/NanumGothic.ttf
          weight: 700

    - family: mywife
      fonts:
        - asset: asset/font/MyWifeBrush.ttf
          weight: 500
